//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscosServidoresEntities : DbContext
    {
        public DiscosServidoresEntities()
            : base("name=DiscosServidoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Disco> Disco { get; set; }
        public DbSet<DiscoTipo> DiscoTipo { get; set; }
        public DbSet<Interprete> Interprete { get; set; }
        public DbSet<Puntuacion> Puntuacion { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
    }
}
