//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Interprete
    {
        public Interprete()
        {
            this.Disco = new HashSet<Disco>();
        }
    
        public string Interprete1 { get; set; }
        public int IdInterprete { get; set; }
        [JsonIgnore]
        public virtual ICollection<Disco> Disco { get; set; }
    }
}
