//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Tipo
    {
        public Tipo()
        {
            this.DiscoTipo = new HashSet<DiscoTipo>();
        }
    
        public int IdTipo { get; set; }
        public string tipo1 { get; set; }
        [JsonIgnore]
        public virtual ICollection<DiscoTipo> DiscoTipo { get; set; }
    }
}
